<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8" >
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="">
      <title>Sistema de Sorteio - TI VAS</title>
      <!-- Bootstrap Core CSS -->
      <link type="text/css" href="/sorteio/app/views/css/bootstrap.min.css" rel="stylesheet" >
      <!-- MetisMenu CSS -->
      <link  type="text/css" href="/sorteio/app/views/css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">
      <!-- Timeline CSS -->
      <link type="text/css" href="/sorteio/app/views/css/plugins/timeline.css" rel="stylesheet">
      <!-- Custom CSS -->
      <link  type="text/css" href="/sorteio/app/views/css/sb-admin-2.css" rel="stylesheet">
      <!-- DataTables CSS -->
      <link type="text/css" href="/sorteio/app/views/css/plugins/dataTables.bootstrap.css" rel="stylesheet">
      <!-- Morris Charts CSS -->
      <link type="text/css" href="/sorteio/app/views/css/plugins/morris.css" rel="stylesheet">
      <!-- Custom Fonts -->
      <link type="text/css" href="/sorteio/app/views/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet">
      <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
    <style type="text/css">
       body{
         background: url("/sorteio/error_pages/images/404space.png") no-repeat top fixed;
         background-color: black;
          -webkit-background-size: cover;
          -moz-background-size: cover;
          -o-background-size: cover;
          background-size: cover;
         htcolor: #333;
         font-size: 18px;
         line-heig: 1.6em;
         font-weight: 300;
      }

      h1{
         font-size: 40px;
         line-height: 1em;
         font-weight: bold;
         font-family: 'ProximaNova-Bold', 'Helvetica-neue', 'Helvetica', Arial, sans-serif;
         text-align: center;
         margin-top: 320px; 
         background-color: rgba(255,255,255,0.3);
         padding: 5px; 
         height: 70px;
       
      }
      .white{
         color: #000;
      }
      h2{
         text-align: center;
         font-size: 50px;
         line-height: 1em;
         font-weight: normal;
         margin-top: 180px;
         margin-left: -70px;
         color: rgba(255,0,0,0.5);
          font-weight: bold;
         font-family: 'ProximaNova-Bold', 'Helvetica-neue', 'Helvetica', Arial, sans-serif;
         text-align: center;
      }
   
   </style>
   </head>
   <body>
<h2>Error </h2>
<h1 class="moveDown entry-title white" style="margin-bottom: 1em;">Parece que você se perdeu no espaço !</h1>


   </body>
   </html>