<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>

    <!-- Bootstrap Core CSS -->
    <link href="/mvc-ouvidoria/app/views/css/bootstrap.min.css" rel="stylesheet">

    <!--admin css -->
    <link href="/mvc-ouvidoria/app/views/css/admin.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/mvc-ouvidoria/app/views/css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/mvc-ouvidoria/app/views/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/mvc-ouvidoria/app/views/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>


<body>

<link href='http://fonts.googleapis.com/css?family=Raleway:400,200' rel='stylesheet' type='text/css'>

<div class="container">
    <div class="row login_box">
        <div class="col-md-12 col-xs-12" align="center">
            <div class="line"><h3><?php echo date("H:i");?> AM</h3></div>
            <div class="outter"><img src="\mvc-ouvidoria\app\views\images\logo-fsa.jpg" class="image-circle"/></div>   
            <h1>Olá Admin</h1>
            <span>FSA</span>
        </div>
      
        <form class="form-horizontal" action="/mvc-ouvidoria/admin/login/acao/logar" method="post">
        <div class="col-md-12 col-xs-12 login_control">
                
                <div class="control">
                    <div class="label">Email Address</div>
                    <input type="text" name="email" class="form-control" placeholder="admin@fsa.com"/>
                </div>
                
                <div class="control">
                     <div class="label">Password</div>
                    <input type="password" name="password" class="form-control" placeholder="******"/>
                </div>
                <div align="center">
                     <button class="btn btn-orange">LOGIN</button>
                </div>
                
        </div>
        </form>
        
        
            
    </div>
</div>

    <!-- jQuery Version 1.11.0 -->
    <script src="js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="js/plugins/metisMenu/metisMenu.min.js"></script>

    <!-- Flot Charts JavaScript -->
    <script src="js/plugins/flot/excanvas.min.js"></script>
    <script src="js/plugins/flot/jquery.flot.js"></script>
    <script src="js/plugins/flot/jquery.flot.pie.js"></script>
    <script src="js/plugins/flot/jquery.flot.resize.js"></script>
    <script src="js/plugins/flot/jquery.flot.tooltip.min.js"></script>
    <script src="js/plugins/flot/flot-data.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/sb-admin-2.js"></script>

</body>

</html>
