<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="utf-8">
    <title>Sistema de Ouvidoria - FSA</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Sistema de Ouvidoria - Fundação Santo Adnre">
    <meta name="author" content="Leandro Cubas de Macedo">
    <link href="https://fonts.googleapis.com/css?family=Limelight|Flamenco|Federo|Yesteryear|Josefin Sans|Spinnaker|Sansita One|Handlee|Droid Sans|Oswald:400,300,700"
    media="screen" rel="stylesheet" type="text/css">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- jQuery and Bootstrap JS -->
    <script src="/mvc-ouvidoria/app/views/js/bootstrap.min.js"></script>
    <script src="/mvc-ouvidoria/app/views/js/plugins/pagination.js"></script>
    <!-- BootstrapValidator CSS -->
    <link href="/mvc-ouvidoria/app/views/css/bootstrap.min.css" rel="stylesheet">
    <link href="/mvc-ouvidoria/app/views/css/plugins/tabela.css" rel="stylesheet">
    <link href="/mvc-ouvidoria/app/views/css/timelineAdmin.css" rel="stylesheet">
     <link href="/mvc-ouvidoria/app/views/css/modal.css" rel="stylesheet">
<!-- BootstrapValidator JS -->
    <script type="text/javascript" src="/mvc-ouvidoria/app/views/js/plugins/bootstrapvalidator/dist/js/bootstrapValidator.min.js"></script>
      <!-- Include all compiled plugins (below), or include individual  files as needed -->
      <!--[if lt IE 9] -->
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <!--[endif]-->
     <script src="/mvc-ouvidoria/app/views/js/modal.js"></script>
  </head>
  

  <body>


  <div class="modal fade" id="Leandro"tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Parabens !</h4>
      </div>
      <div class="modal-body">
        <div class="alert alert-success">
                  <a href="#" class="close" data-dismiss="alert" aria-hidden= "true">&times;</a>
                   <span class="glyphicon glyphicon-ok"></span>
                   <strong> Parabens!</strong>
                   <hr class="message-inner-separator"><p>
                    Seus dados foram Salvos com sucesso.
                  </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
    <div class="img-resposive navbar navbar-default navbar-fixed-top" role="navigation"
    style="padding-left:05px;
             border-radius: 0px;
             background-color:white !important;
             animation:fixNav 1s !important;
             -moz-animation:fixNav 1s !important;
            -webkit-animation:fixNav 1s !important;
             background:rgba(0,0,0,0.2);
            opacity:0.90;
           -moz-opacity: 0.90;
            filter: alpha(opacity=90);" draggable="true">
      <div class="container" style="margin-left:0px;margin-bottom:0px;height:57px; width:100%;
                                      border-radius: 0px;">
        <div class="navbar-header" draggable="true">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
          data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <img src="/mvc-ouvidoria/app/views/images/bolt.png" class="image pull-left img-responsive" style="padding:05px;line-height: 40px;width:40px; margin-top:05px;"
          draggable="true">
          <a class="navbar-brand" href="#" style="text-shadow: none; font-family:oswald;
  font-weight: bold;font-size: 24px;color: #333333;line-height: 40px; padding:05px;margin-left:0px;"
          draggable="true">
            Ouvidoria - Fundação Santo André </a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse" style="padding-right:50px">
          <ul class="nav navbar-nav navbar-right">
            <li class="active" draggable="true">
              <a href="#">Home</a>
            </li>
            <li class="">
              <a href="/mvc-ouvidoria/admin/logout">Logout</a>
            </li>

          </ul>
        </div>
      </div>
    </div>
    <!-- FIM DO NAV -->
    <div class="container-fluid container-fluid-1" style="margin-top:60px;
                                                               border-bottom: 1px solid #dfedeb;
                                                               border-radius: 10px;
                                                               -moz-box-shadow: none;
                                                                            -webkit-box-shadow: none;
                                                                            -o-box-shadow: none;
                                                                             box-shadow: none;
                                                               background: #f5f5f5 url(/mvc-ouvidoria/app/views/images/source.jpg) repeat 0px 0px;
                                                                            background-size:cover;
                                                               height:185px;"
    draggable="true">
      <div class="container-fluid" draggable="true">
        <div class="container" style="padding-top:20px">
          <div class="row-fluid">
            <span class="span12" draggable="true">
              <h1 class="heading" style="background-color:white;
                                           background: rgba(255, 255, 255, 0.631373);
                                           font-family:proxima-nova;
                                           font-size: 68px;
                                           color: #0035a2;
                                           font-weight: bold;
                                           
  line-height: 64px;">Fundação Santo André</h1>
              <p style="background-color:white;
                                           background: rgba(255, 255, 255, 0.631373);
                                           font-family:proxima-nova;
                                           font-size: 22px;
                                           color: #0035a2;
                                           font-weight: bold;" draggable="true">Sistema de Ouvidoria</p>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="container" style="background: rgba(0, 0, 0, 0);  padding: 0px;  border-radius: 0px;  -moz-box-shadow: none;  -webkit-box-shadow: none;
  -o-box-shadow: none;  box-shadow: none;  border-left: none;  border-right: none;  margin-top:15px">
      <div class="col-md-3 column margintop20">
        <ul class="nav nav-pills nav-stacked">
          <li class="active" style="margin-top: 0px;margin-left: 0;border-bottom:1px solid #dadada;border-left:1px solid #dadada;border-right:1px solid #dadada;">
            <a href="/mvc-ouvidoria/Admin"><span class="glyphicon glyphicon-chevron-right"></span>Lista de Protocolos</a>
          </li>
          <li class="" style="margin-top: 0px;margin-left: 0;border-bottom:1px solid #dadada;border-left:1px solid #dadada;border-right:1px solid #dadada;">
            <a href="#" data-toggle="modal" data-target=".bs-modal-sm"><span class="glyphicon glyphicon-chevron-right"></span>Exportar Dados</a>
          </li>
          <li style="margin-top: 0px;margin-left: 0;border-bottom:1px solid #dadada;border-left:1px solid #dadada;border-right:1px solid #dadada;">
            <a href="/mvc-ouvidoria/admin/logout" class="active2"><span class="glyphicon glyphicon-chevron-right"></span> Logout</a>
          </li>
        
        </ul>
      </div>
      <span class="span9">
        <div class="page-header" style="min-width:850;  margin: 50px 0px 10px 100px;font-weight: normal; color: #555555; font-size: 40px;float:left;">
          <h1>Timeline Protocolos </h1>
        </div>
      </span>
<div class="container" style="margin-top:140px">
   <div class="table-responsive">
      <table class="table" id="dataTables-example">
         <thead>
            <tr>
               <th>
                  <div id="timeline">
                     <div class="row timeline-movement timeline-movement-top">
                        <div class="timeline-badge timeline-future-movement">  
                           <a href="#">
                           <span class="glyphicon glyphicon-plus"></span>
                           </a>
                        </div>
                        <div class="timeline-badge timeline-filter-movement">
                           <a href="#">
                           <span class="glyphicon glyphicon-time"></span>
                           </a>
                        </div>
                     </div>
                  </div>
               </th>
            </tr>
         </thead>
         <tbody>
            <?php $contador =0; foreach ($view_lista_protocolos as $protocolos) { ?>
            <tr>
               <td>
                  <div id="timeline">
                     <div class="row timeline-movement">
                        <?php
                           if($protocolos['status'] == 'Finalizado'){ ?>
                        <div class="timeline-badge">
                           <span class="timeline-balloon-date-day"><?php 
                              $data = explode( '-', $protocolos['data_geracao']);
                              echo $data[2]; ?></span>
                           <span class="timeline-balloon-date-month"><?php
                              switch ($data[1]) {
                                 case '01':
                                   echo "JAN";
                                    break;
                                 case '02':
                                   echo "FEV";
                                    break;
                                 case '03':
                                   echo "MARÇO";
                                    break;
                                 case '04':
                                   echo "ABR";
                                    break;
                                 case '05':
                                   echo "MAIO";
                                    break;
                                 case '06':
                                   echo "JUNHO";
                                    break;
                                 case '07':
                                   echo "JULHO";
                                    break;
                                 case '08':
                                   echo "AGO";
                                    break;
                                 case '09':
                                   echo "SET";
                                    break;
                                 case '10':
                                   echo "OUT";
                                    break;
                                 case '11':
                                   echo "NOV";
                                    break;
                                 case '12':
                                   echo "DEZ";
                                    break;
                                 default:
                                    echo "---";
                                    break;
                              } ?>
                           </span>
                        </div>
                        <div class="col-sm-offset-6 col-sm-6  timeline-item">
                           <div class="row">
                              <div class="col-sm-offset-1 col-sm-11">
                                 <div class="timeline-panel debits">
                                    <ul class="timeline-panel-ul">
                                       <li><span class="importo">
                                          <?php echo "<small class='text-muted'> Protocolo - " . $protocolos['protocolo'] . "</small> - " . $protocolos['nome']; ?></span>
                                       </li>
                                       <li><span class="causale"><?php echo $protocolos['manifestacao'] ?></span> </li>
                                       <li>
                                          <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i><?php 
                                             $data = explode( '-', $protocolos['data_geracao']);
                                             echo $data[2]. "-".$data[1]. "-". $data[0]; ?></small></p>
                                       </li>
                                       <li>
                                          <form method="post" action="/mvc-ouvidoria/Admin/AlteraStatusProtocolo/id/<?php echo $protocolos['idprotocolo'] ?>">
                                             <div class="form-group">
                                                <label class="control-label">Status do Protocolo</label>
                                                <div class="col-md-8">
                                                   <select class="form-control" name="status">
                                                      <option value=""><?php echo $protocolos['status'] ?></option>
                                                      <option value="Encaminhado Setor/Unidade">Encaminhado Setor/Unidade</option>
                                                      <option value="Respondido Setor/Unidade">Respondido Setor/Unidade</option>
                                                      <option value="Encaminhado Ouvidoria">Encaminhado Ouvidoria</option>
                                                      <option value="Devolvido Setor/Unidade">Devolvido Setor/Unidade</option>
                                                      <option value="Finalizado">Finalizado</option>
                                                   </select>
                                                </div>
                                                <button type="submit" class="btn btn-warning">Salvar</button>
                                             </div>
                                          </form>
                                       </li>
                                    </ul>
                                 </div>
                              </div>
                           </div>
                        </div>
                        <?php
                           } else { ?>
                        <div class="timeline-badge">
                           <span class="timeline-balloon-date-day"><?php 
                              $data = explode( '-', $protocolos['data_geracao']);
                              echo $data[2]; ?></span>
                           <span class="timeline-balloon-date-month"><?php
                              switch ($data[1]) {
                                 case '01':
                                   echo "JAN";
                                    break;
                                 case '02':
                                   echo "FEV";
                                    break;
                                 case '03':
                                   echo "MARÇO";
                                    break;
                                 case '04':
                                   echo "ABR";
                                    break;
                                 case '05':
                                   echo "MAIO";
                                    break;
                                 case '06':
                                   echo "JUNHO";
                                    break;
                                 case '07':
                                   echo "JULHO";
                                    break;
                                 case '08':
                                   echo "AGO";
                                    break;
                                 case '09':
                                   echo "SET";
                                    break;
                                 case '10':
                                   echo "OUT";
                                    break;
                                 case '11':
                                   echo "NOV";
                                    break;
                                 case '12':
                                   echo "DEZ";
                                    break;
                                 default:
                                    echo "---";
                                    break;
                              } ?>
                           </span>
                        </div>
                        <div class="col-sm-6  timeline-item">
                           <div class="row">
                              <div class="col-sm-11">
                                 <div class="timeline-panel credits">
                                    <ul class="timeline-panel-ul">
                                       <li><span class="importo">
                                          <?php echo "<small class='text-muted'> Protocolo - " . $protocolos['protocolo'] . "</small> - " . $protocolos['nome']; ?></span>
                                       </li>
                                       <li><span class="causale"><?php echo $protocolos['manifestacao'] ?></span> </li>
                                       <li>
                                          <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i><?php 
                                             $data = explode( '-', $protocolos['data_geracao']);
                                             echo $data[2]. "-".$data[1]. "-". $data[0]; ?></small></p>
                                       </li>
                                       <li>
                                          <form method="post" action="/mvc-ouvidoria/Admin/AlteraStatusProtocolo/id/<?php echo $protocolos['idprotocolo'] ?>">
                                             <div class="form-group">
                                                <label class="control-label">Status do Protocolo</label>
                                                <div class="col-md-8">
                                                   <select class="form-control" name="status">
                                                      <option value="<?php echo $protocolos['status'] ?>"><?php echo $protocolos['status'] ?></option>
                                                      <option value="Encaminhado Setor/Unidade">Encaminhado Setor/Unidade</option>
                                                      <option value="Respondido Setor/Unidade">Respondido Setor/Unidade</option>
                                                      <option value="Encaminhado Ouvidoria">Encaminhado Ouvidoria</option>
                                                      <option value="Devolvido Setor/Unidade">Devolvido Setor/Unidade</option>
                                                      <option value="Finalizado">Finalizado</option>
                                                   </select>
                                                </div>
                                                <button type="submit" class="btn btn-success">Salvar</button>
                                             </div>
                                          </form>
                                       </li>
                                    </ul>
                                 </div>
                              </div>
                           </div>
                        </div>
                        <?php } ?>
                     </div>
                     <?php $contador++; }  ?>
                  </div>
               </td>
            </tr>
         </tbody>
      </table>
   </div>
</div>
<!-- fechando div do container -->
    
</div>
    <!--aqui tinha um </span> -->
    <div class="container-fluid" style="background: #333333; padding: 30px 20px 30px 20px;">
      <div class="container">
        <div class="row-fluid">
          <span class="span12">
            <div class="pull-left">
              <p style="font-weight: 300;  color: #ffffff; line-height: 36px;">© Fundação Santo André</p>
            </div>
            <ul class="nav nav-pills pull-right" style=" margin: 0px;">
              <li>
                <a href="#" style="text-align: center;  color: #cccccc;">About</a>
              </li>
              <li>
                <a href="#" style="text-align: center;  color: #cccccc;">Privacy</a>
              </li>
              <li>
                <a href="#" style="text-align: center;  color: #cccccc;">Terms Of Service</a>
              </li>
              <li>
                <a href="#" style="text-align: center;  color: #cccccc;"><?php echo date('Y M D H:m');?></a>
              </li>
            </ul>
          </span>
        </div>
      </div>
    </div>


    <div class="modal fade bs-modal-sm container-fluid" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
         <div class="modal-header">
            <h3><span class="label label-warning" id="qid">Relatorio</span> Quais informações deseja exportar ?</h3>
        </div>
        <div class="modal-body">
            <div class="col-xs-3 col-xs-offset-5">
               <div id="loadbar" style="display: none;">
                  <div class="blockG" id="rotateG_01"></div>
                  <div class="blockG" id="rotateG_02"></div>
                  <div class="blockG" id="rotateG_03"></div>
                  <div class="blockG" id="rotateG_04"></div>
                  <div class="blockG" id="rotateG_05"></div>
                  <div class="blockG" id="rotateG_06"></div>
                  <div class="blockG" id="rotateG_07"></div>
                  <div class="blockG" id="rotateG_08"></div>
              </div>
          </div>

          <div class="quiz" id="quiz" data-toggle="buttons">
           <label class="element-animation1 btn btn-lg btn-primary btn-block"><span class="btn-label"><i class="glyphicon glyphicon-chevron-right"></i></span> <input type="radio" name="q_answer" value="tudo">Todas informações</label>
           <label class="element-animation2 btn btn-lg btn-primary btn-block"><span class="btn-label"><i class="glyphicon glyphicon-chevron-right"></i></span> <input type="radio" name="q_answer" value="protocolos">Somente informações dos Protocolos</label>
           <label class="element-animation3 btn btn-lg btn-primary btn-block"><span class="btn-label"><i class="glyphicon glyphicon-chevron-right"></i></span> <input type="radio" name="q_answer" value="manifestacao">Somente informações da manifestação</label>
           <label class="element-animation4 btn btn-lg btn-primary btn-block"><span class="btn-label"><i class="glyphicon glyphicon-chevron-right"></i></span> <input type="radio" name="q_answer" value="users">Somente dados dos manifestantes</label>
       </div>
   </div>
   <div class="modal-footer text-muted">
    <span id="answer"></span>
    <center>
        <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
   </center>
</div>
</div>
</div>
</div>
   <script src="/mvc-ouvidoria/app/views/js/plugins/dataTables/jquery.dataTables.js"></script>
  <script src="/mvc-ouvidoria/app/views/js/plugins/dataTables/dataTables.bootstrap.js"></script>
      <script>
      //o orignal esta alterado na linha 481 procurar por orginal
         $(document).ready(function() {
             $('#dataTables-example').dataTable();
         });
      </script>
    <!-- aqui encerra a div principal -->
    <script>
      $(document).ready(function() {
                $('#geraProtocolo').bootstrapValidator({
                    // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
                    feedbackIcons: {
                        valid: 'glyphicon glyphicon-ok',
                        invalid: 'glyphicon glyphicon-remove',
                        validating: 'glyphicon glyphicon-refresh'
                    },
                    
                    fields: {
                        nome: {
                            message: 'Insira um nome',
                            validators: {
                                notEmpty: {
                                    message: 'O campo nome nao pode ser deixado em branco'
                                },
                                stringLength: {
                                    min: 3,
                                    max: 30,
                                    message: 'O nome deve conter entre 3 a 30 caracteres'
                                },
                                regexp: {
                                    regexp: /^[a-zA-Z0-9]+$/,
                                    message: 'O nome so pode ser considerado por simbolos alfanumericos'
                                },
                                different: {
                                    field: 'password',
                                    message: 'The username and password cannot be the same as each other'
                                }
                            }
                        },
                       manifestacao: {
                      validators: {
                          notEmpty: {
                              message: 'Por favor escolha uma manfiestação'
                          }
                      }
                  },
                       email: {
                  validators: {
                      notEmpty: {
                          message: 'O email é um campo Obrigatorio'
                      },
                      emailAddress: {
                          message: 'Favor digitar um email valido'
                      }
                  }
              },
                        
                   //       contato: {
                 // threshold: 5,
                  //validators: {
                    //  notEmpty: {
                      //    message: 'The phone number is required'
                      // },
                      // phone: {
                         // message: 'The phone number is not valid',
                         // country: 'BR'
                      // }
                 // }
              // },
                        setor: {
                            validators: {
                                notEmpty: {
                                    message: 'O setor é Obrigatorio'
                                }
                            }
                        },

                        manifest: {
                            validators: {
                                notEmpty: {
                                    message: 'Preencha a sua manifestação'
                                },
                            stringLength: {
                                    min: 10,
                                    max:500,
                                    message: 'O Manifestação deve conter pelo menos Dez caracteres'
                                }
                        }},

                       vinculo: {
                            validators: {
                                notEmpty: {
                                    message: 'O vinculo é Obrigatorio'
                                }
                            }
                        }
                    }
                    
                });
            });
            
            $(document).ready(function() {
            
            });
    </script>


  </body>

</html>