<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="utf-8">
    <title>Sistema de Ouvidoria - FSA</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Sistema de Ouvidoria - Fundação Santo Adnre">
    <meta name="author" content="Leandro Cubas de Macedo">
    <link href="https://fonts.googleapis.com/css?family=Limelight|Flamenco|Federo|Yesteryear|Josefin Sans|Spinnaker|Sansita One|Handlee|Droid Sans|Oswald:400,300,700"
    media="screen" rel="stylesheet" type="text/css">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- jQuery and Bootstrap JS -->
    <script src="/mvc-ouvidoria/app/views/js/bootstrap.min.js"></script>
    <!-- BootstrapValidator CSS -->
    <link href="/mvc-ouvidoria/app/views/css/bootstrap.min.css" rel="stylesheet">
    <link href="/mvc-ouvidoria/app/views/css/plugins/tabela.css" rel="stylesheet">
<!-- BootstrapValidator JS -->
    <script type="text/javascript" src="/mvc-ouvidoria/app/views/js/plugins/bootstrapvalidator/dist/js/bootstrapValidator.min.js"></script>
      <!-- Include all compiled plugins (below), or include individual  files as needed -->
      <!--[if lt IE 9] -->
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <!--[endif]-->
  </head>

  <body>
    <div class="img-resposive navbar navbar-default navbar-fixed-top" role="navigation"
    style="padding-left:05px;
             border-radius: 0px;
             background-color:white !important;
             animation:fixNav 1s !important;
             -moz-animation:fixNav 1s !important;
            -webkit-animation:fixNav 1s !important;
           	 background:rgba(0,0,0,0.2);
	         opacity:0.90;
	        -moz-opacity: 0.90;
	         filter: alpha(opacity=90);" draggable="true">
      <div class="container" style="margin-left:0px;margin-bottom:0px;height:57px; width:100%;
                                      border-radius: 0px;">
        <div class="navbar-header" draggable="true">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
          data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <img src="/mvc-ouvidoria/app/views/images/bolt.png" class="image pull-left img-responsive" style="padding:05px;line-height: 40px;width:40px; margin-top:05px;"
          draggable="true">
          <a class="navbar-brand" href="#" style="text-shadow: none; font-family:oswald;
  font-weight: bold;font-size: 24px;color: #333333;line-height: 40px; padding:05px;margin-left:0px;"
          draggable="true">
            Ouvidoria - Fundação Santo André </a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse" style="padding-right:50px">
          <ul class="nav navbar-nav navbar-right">
            <li class="active" draggable="true">
              <a href="#">Home</a>
            </li>
            <li class="">
              <a href="/mvc-ouvidoria/index/logout">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!-- FIM DO NAV -->
    <div class="container-fluid container-fluid-1" style="margin-top:60px;
                                                               border-bottom: 1px solid #dfedeb;
                                                               border-radius: 10px;
                                                               -moz-box-shadow: none;
  															                               -webkit-box-shadow: none;
  															                               -o-box-shadow: none;
  			 											   	                             box-shadow: none;
                                                               background: #f5f5f5 url(/mvc-ouvidoria/app/views/images/source.jpg) repeat 0px 0px;
  															                               background-size:cover;
                                                               height:185px;"
    draggable="true">
      <div class="container-fluid" draggable="true">
        <div class="container" style="padding-top:20px">
          <div class="row-fluid">
            <span class="span12" draggable="true">
              <h1 class="heading" style="background-color:white;
                                           background: rgba(255, 255, 255, 0.631373);
                                           font-family:proxima-nova;
                                           font-size: 68px;
                                           color: #0035a2;
                                           font-weight: bold;
                                           
  line-height: 64px;">Fundação Santo André</h1>
              <p style="background-color:white;
                                           background: rgba(255, 255, 255, 0.631373);
                                           font-family:proxima-nova;
                                           font-size: 22px;
                                           color: #0035a2;
                                           font-weight: bold;" draggable="true">Sistema de Ouvidoria</p>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="container" style="background: rgba(0, 0, 0, 0);  padding: 0px;  border-radius: 0px;  -moz-box-shadow: none;  -webkit-box-shadow: none;
  -o-box-shadow: none;  box-shadow: none;  border-left: none;  border-right: none;  margin-top:15px">
      <div class="col-md-3 column margintop20">
        <ul class="nav nav-pills nav-stacked">
          <li class="active" style="margin-top: 0px;margin-left: 0;border-bottom:1px solid #dadada;border-left:1px solid #dadada;border-right:1px solid #dadada;">
            <a href="#"><span class="glyphicon glyphicon-chevron-right"></span> Abrir Manifestação</a>
          </li>
          <li style="margin-top: 0px;margin-left: 0;border-bottom:1px solid #dadada;border-left:1px solid #dadada;border-right:1px solid #dadada;">
            <a href="/mvc-ouvidoria/Protocolo/"><span class="glyphicon glyphicon-chevron-right"></span> Consultar Protocolo</a>
          </li>
          <li style="margin-top: 0px;margin-left: 0;border-bottom:1px solid #dadada;border-left:1px solid #dadada;border-right:1px solid #dadada;">
            <a href="/mvc-ouvidoria/index/logout" class="active2"><span class="glyphicon glyphicon-chevron-right"></span> Logout</a>
          </li>
        
        </ul>
      </div>
      <span class="span9">
        <div class="page-header" style="min-width:850;  margin: -10px 0px 10px 0px;font-weight: normal; color: #555555; font-size: 40px;float:left;">
          <h1>Preencha os campos abaixo
            <small style="font-size: 26px;  line-height: 42px;">Ouvidoria FSA</small>
          </h1>
        </div>
        <div class="well img-responsive" style="padding: 25px 19px 5px 19px;border-radius: 15px; min-height: 300px;font-size: 10pt;
  font-family:droid sans;  font-weight: bold;float:left;" draggable="true">
        
          <form id="geraProtocolo" method="post" class="form-horizontal img-responsive" action="/mvc-ouvidoria/sistema/cadastrar" style="width: 760px;" draggable="true" role="form">
            <!-- <input type="hidden" name="acao"  value="gerar_protocolo">
              <div class="form-group " draggable="true">
                <label class="col-lg-3 control-label ">Nome</label>
                  <div class="col-lg-5">
                    <input type="text" required="required" class="form-control" name="nome">
                  </div>
              </div>
              
              <div class="form-group" draggable="true">
                <label class="col-lg-3 control-label">Email</label>
                  <div class="col-lg-5">
                    <input type="email" required="required"class="form-control" name="email">
                  </div>
              </div>
              <div class="form-group">
                <label class="col-lg-3 control-label">Telefone</label>
                  <div class="col-lg-5">
                    <input type="text" class="form-control" name="contato" placeholder="(xx) xxxx-xxxx">
                  </div>
              </div> -->
              <div class="form-group" style="margin-left:60px" draggable="true">
                <div class="controls" draggable="true">
                  <input type="checkbox" name="check_sigilo" value="s" checked>Desejo que meus dados sejam mantidos em sigilo
                </div>
              </div><!-- adicionei este -->
                <br>

                
              
            <div class="form-group" draggable="true">
                <label class="col-md-3 control-label">Tipo de Manifestação</label>
                <div class="col-md-5">
                  <select class="form-control" name="manifestacao">
                    <option value="">Escolha uma manifestação</option>
                      <option value="Critica">Crítica</option>
                      <option value="Denuncia">Denúncia</option>
                      <option value="Elogio">Elogio</option>
                      <option value="Reclamacao">Reclamação</option>
                      <option value="Sugestao">Sugestão</option>
                      </select>
                  </div>
            </div>
            
            <!-- close control group -->
            <div class="row" style="margin-right:-25px;">
              <label class="col-md-3 control-label"  style="margin-left:10px;">Vínculo do Manifestante</label>
              <div class="col-md-5 form-group">
                <select class="form-control" name="vinculo" required="required">
                  <option value="">Escolha um vinculo</option>
                  <option value="Aluno">Aluno</option>
                  <option value="Funcionario_Administrativo">Funcionario Administrativo</option>
                  <option value="Funcionario_docente">Funcionario Docente</option>
                  <option value="Funcionario_externo">Outros - Indique campo ao lado</option>
                </select>
              </div>
              <div class="col-sm-4">
              <input maxlength="200" type="text"  class="form-control" placeholder="OUTROS" name="outros" />
              </div>
            </div> 
   
            <div class="form-group">
              <label class="col-md-3 control-label">Escolha o Setor/Unidade</label>
              <div class="col-md-5">
                <select class="form-control" name="setor">
                  <option value="">Escolha um Setor/Unidade</option>
                  <option value="Almoxarifado">Almoxarifado</option>
                  <option value="Ambulatorio">Ambulatorio</option>
                  <option value="Arrecadação">Arrecadação</option>
                  <option value="Acessoria de Gabinete da Reitoria">Acessoria de Gabinete da Reitoria</option>
                  <option value="Atlética">Atlética</option>
                  <option value="Biblioteca">Biblioteca</option>
                  <option value="Biotério">Biotério</option>
                  <option value="Cantinas">Cantinas</option>
                  <option value="Centro de Informação">Centro de Informação</option>
                  <option value="Cobrança">Cobrança</option>
                  <option value="Colégio - Diretoria">Colégio - Diretoria</option>
                  <option value="Colégio - Docentes">Colégio - Docentes</option>
                  <option value="Colégio - Secretaria">Colégio - Secretaria</option>
                  <option value="Compras">Compras</option>
                  <option value="Comunicação">Comunicação</option>
                  <option value="Concursos">Concursos</option>
                  <option value="Cozinha">Cozinha</option>
                  <option value="Eventos">Eventos</option>
                  <option value="FAECO - Central de Estágios">FAECO - Central de Estágios</option>
                  <option value="FAECO - Diretoria">FAECO - Diretoria</option>
                  <option value="FAECO - Docentes">FAECO - Docentes</option>
                  <option value="FAECO - Secretária">FAECO - Secretária</option>
                  <option value="FAENG - Central de Estágios">FAENG - Central de Estágios</option>
                  <option value="FAENG - Diretoria">FAENG - Diretoria</option>
                  <option value="FAENG - Docentes">FAENG - Docentes</option>
                  <option value="FAENG - Secretaria">FAENG - Secretaria</option>
                  <option value="FAFIL - Central de Estágios">FAFIL - Central de Estágios</option>
                  <option value="FAFIL - Diretoria">FAFIL - Diretoria</option>
                  <option value="FAFIL - Docentes">FAFIL - Docentes</option>
                  <option value="FAFIL - Secretaria">FAFIL - Secretaria</option>
                  <option value="Financeiro">Financeiro</option>
                  <option value="Laboratórios">Laboratórios</option>
                  <option value="Limpeza">Limpeza</option>
                  <option value="Marcenaria">Marcenaria</option>
                  <option value="Patrimônio">Patrimônio</option>
                  <option value="Portaria">Portaria</option>
                  <option value="Pós-Graduação - Docentes">Pós-Graduação - Docentes</option>
                  <option value="Pós-Graduação - Sectraria">Pós-Graduação - Sectraria</option>
                  <option value="PROAP">PROAP</option>
                  <option value="PROGRAD">PROGRAD</option>
                  <option value="PROPPEX">PROPPEX</option>
                  <option value="Recursos Humanos">Recursos Humanos</option>
                  <option value="Reitoria">Reitoria</option>
                  <option value="Sala de Projetos">Sala de Projetos</option>
                  <option value="Secretaria de Assunto Juridico">Secretaria de Assunto Juridico</option>
                  <option value="Secretaria Geral">Secretaria Geral</option>
                  <option value="Serviço Social">Serviço Social</option>
                </select>
              </div>
            </div>
         
         
              <div class="form-group" draggable="true">
                <label class="col-md-3 control-label">Manifestação</label>
                  <div class="col-md-5">
                    <textarea class="form-control" name="manifest" rows="4" style="height: 90px; max-width:350px"
                    placeholder="Digite aqui sua manifestação !"></textarea>
                  </div>
              </div>
               <div class="form-group">
                <div class="col-lg-6 col-lg-offset-5">
                <!-- Do NOT use name="submit" or id="submit" for the Submit button -->
                  <button type="submit" class="btn btn-primary" style="align:center;font-family:droid sans;
  border: 1px solid rgba(0, 0, 0, 0.0980392);" draggable="true">Enviar</button>
               
                </div>
              </div>


                </div>
              
            </div>

          </form>

        </div>
      </span>
    </div>
    <!--aqui tinha um </span> -->
    <div class="container-fluid" style="background: #333333; padding: 30px 20px 30px 20px;">
      <div class="container">
        <div class="row-fluid">
          <span class="span12">
            <div class="pull-left">
              <p style="font-weight: 300;  color: #ffffff; line-height: 36px;">© Fundação Santo André</p>
            </div>
            <ul class="nav nav-pills pull-right" style=" margin: 0px;">
              <li>
                <a href="#" style="text-align: center;  color: #cccccc;">About</a>
              </li>
              <li>
                <a href="#" style="text-align: center;  color: #cccccc;">Privacy</a>
              </li>
              <li>
                <a href="#" style="text-align: center;  color: #cccccc;">Terms Of Service</a>
              </li>
              <li>
                <a href="#" style="text-align: center;  color: #cccccc;"><?php echo date('Y M D H:m');?></a>
              </li>
            </ul>
          </span>
        </div>
      </div>
    </div>
    
    <!-- aqui encerra a div principal -->
    <script>
      $(document).ready(function() {
                $('#geraProtocolo').bootstrapValidator({
                    // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
                    feedbackIcons: {
                        valid: 'glyphicon glyphicon-ok',
                        invalid: 'glyphicon glyphicon-remove',
                        validating: 'glyphicon glyphicon-refresh'
                    },
                    
                    fields: {
                        nome: {
                            message: 'Insira um nome',
                            validators: {
                                notEmpty: {
                                    message: 'O campo nome nao pode ser deixado em branco'
                                },
                                stringLength: {
                                    min: 3,
                                    max: 30,
                                    message: 'O nome deve conter entre 3 a 30 caracteres'
                                },
                                regexp: {
                                    regexp: /^[a-zA-Z0-9]+$/,
                                    message: 'O nome so pode ser considerado por simbolos alfanumericos'
                                },
                                different: {
                                    field: 'password',
                                    message: 'The username and password cannot be the same as each other'
                                }
                            }
                        },
                       manifestacao: {
                      validators: {
                          notEmpty: {
                              message: 'Por favor escolha uma manfiestação'
                          }
                      }
                  },
                       email: {
                  validators: {
                      notEmpty: {
                          message: 'O email é um campo Obrigatorio'
                      },
                      emailAddress: {
                          message: 'Favor digitar um email valido'
                      }
                  }
              },
                        
                   //       contato: {
                 // threshold: 5,
                  //validators: {
                    //  notEmpty: {
                      //    message: 'The phone number is required'
                      // },
                      // phone: {
                         // message: 'The phone number is not valid',
                         // country: 'BR'
                      // }
                 // }
              // },
                        setor: {
                            validators: {
                                notEmpty: {
                                    message: 'O setor é Obrigatorio'
                                }
                            }
                        },

                        manifest: {
                            validators: {
                                notEmpty: {
                                    message: 'Preencha a sua manifestação'
                                },
                            stringLength: {
                                    min: 10,
                                    max:500,
                                    message: 'O Manifestação deve conter pelo menos Dez caracteres'
                                }
                        }},

                       vinculo: {
                            validators: {
                                notEmpty: {
                                    message: 'O vinculo é Obrigatorio'
                                }
                            }
                        }
                    }
                    
                });
            });
            
            $(document).ready(function() {
            
            });
    </script>


  </body>

</html>